name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Publish Features
        uses: devcontainers/action@v1
        with:
          generate-docs: true
          publish-features: true
          base-path-to-features: ./src
          publish-to-oci: true
          oci-registry: ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}