name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Smoke test
        uses: devcontainers/action@v1
        with:
          generate-docs: false
          base-path-to-features: ./src
          test-features: true
          features: 'claude-code'
          skip-scenarios: false