name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate devcontainer features
        uses: devcontainers/action@v1
        with:
          validate-only: true
          base-path-to-features: ./src
          
  test:
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      matrix:
        features:
          - claude-code
        baseImage:
          - mcr.microsoft.com/devcontainers/base:ubuntu
    steps:
      - uses: actions/checkout@v4

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test feature
        run: |
          echo "Testing ${{ matrix.features }} feature"
          devcontainer features test \
            --skip-scenarios \
            --features ${{ matrix.features }} \
            --base-image ${{ matrix.baseImage }} \
            .