name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install DevContainer CLI
        run: npm install -g @devcontainers/cli
      
      - name: Test Feature
        run: |
          devcontainer features test \
            --features claude-code \
            --base-image mcr.microsoft.com/devcontainers/base:debian